/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab4;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author QUYEN
 */
public class ChuongTrinhQuanLySach extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    
    public ChuongTrinhQuanLySach() {
        initComponents();
        jtbSach.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                view();
            }
        });
        setTitle("Chương trình quản lý sách");
        // Khởi tạo DefaultTableModel với các cột tương ứng
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Mã sách");
        tableModel.addColumn("Tên sách");
        tableModel.addColumn("Giá");
        tableModel.addColumn("Tác giả");
        tableModel.addColumn("Nhà xuất bản");
        // Thêm dữ liệu mẫu vào DefaultTableModel
        tableModel.addRow(new Object[]{"S001", "Nhà Giả Kim", 150000, "Paulo Coelho", "NXB Văn Học"});
        tableModel.addRow(new Object[]{"S002", "Harry Potter và Hòn Đá Phù Thủy", 220000, "J.K. Rowling", "NXB Trẻ"});
        tableModel.addRow(new Object[]{"S003", "Dấu Chân Trên Cát", 135000, "Nguyễn Ngọc Tư", "NXB Thanh Niên"});
        tableModel.addRow(new Object[]{"S004", "Số Đỏ", 98000, "Nguyễn Nhật Ánh", "NXB Kim Đồng"});
        tableModel.addRow(new Object[]{"S005", "To Kill a Mockingbird", 180000, "Harper Lee", "NXB Lao Động"});
        tableModel.addRow(new Object[]{"S006", "Đắc Nhân Tâm", 120000, "Dale Carnegie", "NXB Thế Giới"});
        tableModel.addRow(new Object[]{"S007", "Bí Mật Tư Duy Triệu Phú", 195000, "T. Harv Eker", "NXB Trí Việt"});
        tableModel.addRow(new Object[]{"S008", "Người Mẹ Tốt Hơn Là Người Thầy Tốt", 89000, "Nguyễn Hoàng Giang", "NXB Giáo Dục"});
        tableModel.addRow(new Object[]{"S009", "Dế Mèn Phiêu Lưu Ký", 75000, "Tô Hoài", "NXB Trẻ"});
        tableModel.addRow(new Object[]{"S010", "Cuốn Theo Chiều Gió", 210000, "Margaret Mitchell", "NXB Văn Học"});
        
        
        // Hiển thị dữ liệu trên jTable_Sach
        jtbSach.setModel(tableModel);
        
        //Tạo file CSV
        createCsvFileIfNeeded();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnDanhSachSach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbSach = new javax.swing.JTable();
        jbtXoa = new javax.swing.JButton();
        jbtThem = new javax.swing.JButton();
        jbtLua = new javax.swing.JButton();
        jbtSua = new javax.swing.JButton();
        jbtTim = new javax.swing.JButton();
        jbtClear = new javax.swing.JButton();
        jbtThoat = new javax.swing.JButton();
        jlbGia = new javax.swing.JLabel();
        jlbMaSach = new javax.swing.JLabel();
        jlbTacGia = new javax.swing.JLabel();
        jlbNXB = new javax.swing.JLabel();
        jlbTenSach = new javax.swing.JLabel();
        jtfNhaXuatBan = new javax.swing.JTextField();
        jtfMaSach = new javax.swing.JTextField();
        jtfTacGia = new javax.swing.JTextField();
        jtfGia = new javax.swing.JTextField();
        jtfTenSach = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(192, 192, 192));
        jPanel1.setForeground(new java.awt.Color(211, 211, 211));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Georgia Pro Black", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin sách");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jpnDanhSachSach.setBackground(new java.awt.Color(192, 192, 192));
        jpnDanhSachSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setBackground(new java.awt.Color(192, 192, 192));
        jScrollPane1.setForeground(new java.awt.Color(211, 211, 211));

        jtbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Giá", "Tác giả", "Nhà xuất bản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbSach);

        javax.swing.GroupLayout jpnDanhSachSachLayout = new javax.swing.GroupLayout(jpnDanhSachSach);
        jpnDanhSachSach.setLayout(jpnDanhSachSachLayout);
        jpnDanhSachSachLayout.setHorizontalGroup(
            jpnDanhSachSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );
        jpnDanhSachSachLayout.setVerticalGroup(
            jpnDanhSachSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        jbtXoa.setBackground(new java.awt.Color(173, 216, 230));
        jbtXoa.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jbtXoa.setText("Xóa");
        jbtXoa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtXoaActionPerformed(evt);
            }
        });

        jbtThem.setBackground(new java.awt.Color(173, 216, 230));
        jbtThem.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jbtThem.setText("Thêm");
        jbtThem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemActionPerformed(evt);
            }
        });

        jbtLua.setBackground(new java.awt.Color(173, 216, 230));
        jbtLua.setText("Lưu");
        jbtLua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtLua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLuaActionPerformed(evt);
            }
        });

        jbtSua.setBackground(new java.awt.Color(173, 216, 230));
        jbtSua.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jbtSua.setText("Sửa");
        jbtSua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSuaActionPerformed(evt);
            }
        });

        jbtTim.setBackground(new java.awt.Color(173, 216, 230));
        jbtTim.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jbtTim.setText("Tìm");
        jbtTim.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTimActionPerformed(evt);
            }
        });

        jbtClear.setBackground(new java.awt.Color(173, 216, 230));
        jbtClear.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jbtClear.setText("Clear");
        jbtClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtClearActionPerformed(evt);
            }
        });

        jbtThoat.setBackground(new java.awt.Color(173, 216, 230));
        jbtThoat.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jbtThoat.setText("Thoát");
        jbtThoat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThoatActionPerformed(evt);
            }
        });

        jlbGia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbGia.setText("Giá");

        jlbMaSach.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbMaSach.setText("Mã sách");

        jlbTacGia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbTacGia.setText("Tác giả");

        jlbNXB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbNXB.setText("Nhà xuất bản");

        jlbTenSach.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbTenSach.setText("Tên sách");

        jtfNhaXuatBan.setBackground(new java.awt.Color(222, 222, 222));

        jtfMaSach.setBackground(new java.awt.Color(222, 222, 222));

        jtfTacGia.setBackground(new java.awt.Color(222, 222, 222));

        jtfGia.setBackground(new java.awt.Color(222, 222, 222));

        jtfTenSach.setBackground(new java.awt.Color(222, 222, 222));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpnDanhSachSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtThem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jbtXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(jbtSua, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jbtLua, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jbtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jbtClear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jbtThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbGia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfGia, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlbNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlbTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfTacGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNhaXuatBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpnDanhSachSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSua, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtLua, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtClear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtThem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void view(){
            int selectedRow=jtbSach.getSelectedRow();
            
            if(selectedRow!=-1){
            this.jtfMaSach.setText(jtbSach.getValueAt(selectedRow, 0).toString());
            this.jtfTenSach.setText(jtbSach.getValueAt(selectedRow, 1).toString());
            this.jtfGia.setText(jtbSach.getValueAt(selectedRow, 2).toString());
            this.jtfTacGia.setText(jtbSach.getValueAt(selectedRow, 3).toString());
            this.jtfNhaXuatBan.setText(jtbSach.getValueAt(selectedRow, 4).toString());
           
            }
        }
    private void clearFields() {
        jtfMaSach.setText(null);
        jtfTenSach.setText(null);
        jtfGia.setText(null);
        jtfTacGia.setText(null);
        jtfNhaXuatBan.setText(null);
    }
    
    private void saveDataToFile() {
    try (BufferedWriter writer = new BufferedWriter(new FileWriter("books.csv"))) {
        // Lấy số hàng và số cột trong bảng
        int rowCount = tableModel.getRowCount();
        int columnCount = tableModel.getColumnCount();

        // Ghi tiêu đề cột vào file CSV
        for (int i = 0; i < columnCount; i++) {
            writer.write(tableModel.getColumnName(i));
            if (i < columnCount - 1) {
                writer.write(",");
            }
        }
        writer.newLine();

        // Ghi dữ liệu từ bảng vào file CSV
        for (int row = 0; row < rowCount; row++) {
            for (int col = 0; col < columnCount; col++) {
                writer.write(String.valueOf(tableModel.getValueAt(row, col)));
                if (col < columnCount - 1) {
                    writer.write(",");
                }
            }
            writer.newLine();
        }

        JOptionPane.showMessageDialog(this, "Dữ liệu đã được lưu vào file.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Lỗi khi lưu dữ liệu vào file.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}
    
    private void createCsvFileIfNeeded() {
    try {
        File file = new File("books.csv");
        if (!file.exists()) {
            file.createNewFile();
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Không thể tạo file CSV.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

    private void jbtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtXoaActionPerformed
        // TODO add your handling code here:
        //Lấy vị trí đang chọn trên jtable
        int indexTB = jtbSach.getSelectedRow();
        //hiển thị hộp thoại xác nhận xóa
        int ret=JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa không?","Xác nhận xóa",   JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION) 
        //Xóa dòng đang chọn ra khỏi jtable
            tableModel.removeRow(indexTB);
        saveDataToFile();
    }//GEN-LAST:event_jbtXoaActionPerformed

    private void jbtThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtThoatActionPerformed
    
    private void jbtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_jbtClearActionPerformed

    private void jbtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTimActionPerformed
        // TODO add your handling code here:
        String masach = jtfMaSach.getText();
        
        boolean found = false;
        for(int i=0; i<tableModel.getRowCount();i++){
            String s = (String)tableModel.getValueAt(i,0);
            if(masach.equals(s)){
                jtfTenSach.setText(tableModel.getValueAt(i,1).toString());
                jtfTacGia.setText( tableModel.getValueAt(i,3).toString());
                jtfNhaXuatBan.setText( tableModel.getValueAt(i,4).toString());
                jtfGia.setText(tableModel.getValueAt(i,2).toString());
       
                found=true;
                break;
            }
            
      
        }
        
       if(found==false){
           JOptionPane.showMessageDialog(this,"Không tìm thấy sách có mã " + masach, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           jtfTenSach.setText("");
            jtfTacGia.setText("");
            jtfNhaXuatBan.setText("");
            jtfGia.setText("");
       }
    }//GEN-LAST:event_jbtTimActionPerformed

    private void jbtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSuaActionPerformed
        // TODO add your handling code here:
        int indexTB = jtbSach.getSelectedRow();
        
        
        int ref=JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn sửa không?","Xác nhận sửa",JOptionPane.YES_NO_OPTION);
        if(ref==JOptionPane.YES_OPTION){
        tableModel.setValueAt(jtfTenSach.getText(),indexTB,1);
        tableModel.setValueAt(jtfGia.getText(),indexTB,2);
        tableModel.setValueAt(jtfTacGia.getText(),indexTB,3);
        tableModel.setValueAt(jtfNhaXuatBan.getText(),indexTB,4);
        }
        saveDataToFile();
    }//GEN-LAST:event_jbtSuaActionPerformed

    private void jbtLuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtLuaActionPerformed

    private void jbtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemActionPerformed
        // TODO add your handling code here:
        String row[] = new String[5];
        //lấy các giá trị ở textfield đưa vào bảng
        row[0]= jtfMaSach.getText();
        row[1]=jtfTenSach.getText();
        row[2]=jtfTacGia.getText();
        row[3]=jtfNhaXuatBan.getText();
        row[4]=jtfGia.getText();
        double gia = 0.0;
        
        //kiểm tra đầy đủ thông tin
        if(row[0].isEmpty() || row[1].isEmpty()|| row[2].isEmpty() || row[3].isEmpty() || row[4].isEmpty()){
            JOptionPane.showConfirmDialog(this,"Vui lòng nhập đủ thông tin","Lỗi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //kiểm tra điều kiện giá không phải số
        try {
            gia=Double.parseDouble(row[4]);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,"Giá phải là một số","Lỗi",JOptionPane.ERROR_MESSAGE);
            return;            
        }
        
        //kiểm tra điều kiện trùng mã sách
        for(int i=0;i<tableModel.getRowCount();i++){
            if(tableModel.getValueAt(i,0).equals(row[0])){
                JOptionPane.showMessageDialog(this,"Mã sách đã tồn tại","Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        tableModel.addRow(row);
        saveDataToFile();
    }//GEN-LAST:event_jbtThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showTableData() {
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuongTrinhQuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuongTrinhQuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuongTrinhQuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuongTrinhQuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChuongTrinhQuanLySach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtClear;
    private javax.swing.JButton jbtLua;
    private javax.swing.JButton jbtSua;
    private javax.swing.JButton jbtThem;
    private javax.swing.JButton jbtThoat;
    private javax.swing.JButton jbtTim;
    private javax.swing.JButton jbtXoa;
    private javax.swing.JLabel jlbGia;
    private javax.swing.JLabel jlbMaSach;
    private javax.swing.JLabel jlbNXB;
    private javax.swing.JLabel jlbTacGia;
    private javax.swing.JLabel jlbTenSach;
    private javax.swing.JPanel jpnDanhSachSach;
    private javax.swing.JTable jtbSach;
    private javax.swing.JTextField jtfGia;
    private javax.swing.JTextField jtfMaSach;
    private javax.swing.JTextField jtfNhaXuatBan;
    private javax.swing.JTextField jtfTacGia;
    private javax.swing.JTextField jtfTenSach;
    // End of variables declaration//GEN-END:variables
}
